import { MakeLogicType, actions, afterMount, kea, key, listeners, path, props, reducers } from 'kea'
import posthog from 'posthog-js'

import { ApiError } from 'lib/api-error'
import type { DashboardsFilters } from 'scenes/dashboard/dashboards/dashboardsLogic'

import * as api from 'products/dashboards/frontend/generated/api'
import type { DashboardSavedViewApi } from 'products/dashboards/frontend/generated/api.schemas'

export type DashboardListSavedView = Omit<DashboardSavedViewApi, 'filters'> & { filters: DashboardsFilters }
export type DashboardSavedViewScope = NonNullable<DashboardListSavedView['scope']>

export interface DashboardSavedViewsPage {
    views: DashboardListSavedView[]
    nextCursor: string | null
}

export interface DashboardSavedViewsLogicProps {
    teamId: number | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface dashboardSavedViewsLogicValues {
    dashboardSavedViewsEnabled: boolean
    loadMoreSavedViewsLoading: boolean
    savedViews: DashboardListSavedView[]
    savedViewsLoadError: boolean
    savedViewsLoadMoreFailed: boolean
    savedViewsLoading: boolean
    savedViewsNextCursor: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface dashboardSavedViewsLogicActions {
    loadMoreSavedViews: () => {
        value: true
    }
    loadMoreSavedViewsFailure: (
        message: string,
        errorObject: unknown
    ) => {
        errorObject: unknown
        message: string
    }
    loadMoreSavedViewsSuccess: (page: DashboardSavedViewsPage) => {
        page: DashboardSavedViewsPage
    }
    loadSavedViews: () => {
        value: true
    }
    loadSavedViewsFailure: (
        message: string,
        errorObject: unknown
    ) => {
        errorObject: unknown
        message: string
    }
    loadSavedViewsSuccess: (page: DashboardSavedViewsPage) => {
        page: DashboardSavedViewsPage
    }
    savedViewCreated: (view: DashboardListSavedView) => {
        view: DashboardListSavedView
    }
    savedViewDeleted: (id: string) => {
        id: string
    }
    savedViewUpdated: (view: DashboardListSavedView) => {
        view: DashboardListSavedView
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface dashboardSavedViewsLogicMeta {
    key: number | 'no-team'
}

export type dashboardSavedViewsLogicType = MakeLogicType<
    dashboardSavedViewsLogicValues,
    dashboardSavedViewsLogicActions,
    DashboardSavedViewsLogicProps,
    dashboardSavedViewsLogicMeta
>

const emptySavedViewsPage: DashboardSavedViewsPage = { views: [], nextCursor: null }

function isSavedViewsUnavailableError(error: unknown): boolean {
    return error instanceof ApiError && (error.status === 403 || error.status === 404)
}

function savedViewsPage(response: Awaited<ReturnType<typeof api.dashboardSavedViewsList>>): DashboardSavedViewsPage {
    return {
        views: response.results as unknown as DashboardListSavedView[],
        nextCursor: response.next ? new URL(response.next).searchParams.get('cursor') : null,
    }
}

export async function loadDashboardSavedViews(teamId: number, cursor?: string): Promise<DashboardSavedViewsPage> {
    return savedViewsPage(await api.dashboardSavedViewsList(String(teamId), { limit: 100, cursor }))
}

export const dashboardSavedViewsLogic = kea<dashboardSavedViewsLogicType>([
    props({} as DashboardSavedViewsLogicProps),
    key((props) => props.teamId ?? 'no-team'),
    path(['products', 'dashboards', 'saved-views', 'dashboardSavedViewsLogic']),
    actions({
        loadSavedViews: true,
        loadSavedViewsSuccess: (page: DashboardSavedViewsPage) => ({ page }),
        loadSavedViewsFailure: (message: string, errorObject: unknown) => ({ message, errorObject }),
        loadMoreSavedViews: true,
        loadMoreSavedViewsSuccess: (page: DashboardSavedViewsPage) => ({ page }),
        loadMoreSavedViewsFailure: (message: string, errorObject: unknown) => ({ message, errorObject }),
        savedViewCreated: (view: DashboardListSavedView) => ({ view }),
        savedViewUpdated: (view: DashboardListSavedView) => ({ view }),
        savedViewDeleted: (id: string) => ({ id }),
    }),
    reducers(({ props }) => ({
        dashboardSavedViewsEnabled: [
            props.teamId != null,
            {
                loadSavedViewsSuccess: () => true,
                loadSavedViewsFailure: (_, { errorObject }) => !isSavedViewsUnavailableError(errorObject),
                loadMoreSavedViewsFailure: (_, { errorObject }) => !isSavedViewsUnavailableError(errorObject),
            },
        ],
        savedViewsNextCursor: [
            null as string | null,
            {
                loadSavedViews: () => null,
                loadSavedViewsSuccess: (_, { page }) => page.nextCursor,
                loadMoreSavedViewsSuccess: (_, { page }) => page.nextCursor,
            },
        ],
        savedViewsLoadError: [
            false,
            {
                loadSavedViews: () => false,
                loadSavedViewsFailure: (_, { errorObject }) => !isSavedViewsUnavailableError(errorObject),
                loadMoreSavedViewsFailure: (_, { errorObject }) => !isSavedViewsUnavailableError(errorObject),
                loadSavedViewsSuccess: () => false,
            },
        ],
        savedViewsLoadMoreFailed: [
            false,
            {
                loadSavedViews: () => false,
                loadMoreSavedViews: () => false,
                loadMoreSavedViewsFailure: () => true,
                loadMoreSavedViewsSuccess: () => false,
            },
        ],
        savedViewsLoading: [
            false,
            { loadSavedViews: () => true, loadSavedViewsFailure: () => false, loadSavedViewsSuccess: () => false },
        ],
        loadMoreSavedViewsLoading: [
            false,
            {
                loadMoreSavedViews: () => true,
                loadMoreSavedViewsFailure: () => false,
                loadMoreSavedViewsSuccess: () => false,
            },
        ],
        savedViews: [
            [] as DashboardListSavedView[],
            {
                loadSavedViews: () => [],
                loadSavedViewsSuccess: (_, { page }) => page.views,
                loadMoreSavedViewsSuccess: (views, { page }) => {
                    const ids = new Set(views.map((view) => view.id))
                    return [...views, ...page.views.filter((view) => !ids.has(view.id))]
                },
                savedViewCreated: (views, { view }) => [...views, view],
                savedViewUpdated: (views, { view }) => views.map((item) => (item.id === view.id ? view : item)),
                savedViewDeleted: (views, { id }) => views.filter((view) => view.id !== id),
            },
        ],
    })),
    listeners(({ actions, props, values }) => ({
        loadSavedViews: async (_, breakpoint) => {
            if (props.teamId == null) {
                actions.loadSavedViewsSuccess(emptySavedViewsPage)
                return
            }
            try {
                const page = await loadDashboardSavedViews(props.teamId)
                breakpoint()
                actions.loadSavedViewsSuccess(page)
            } catch (error) {
                if (!isSavedViewsUnavailableError(error)) {
                    posthog.captureException(error)
                }
                actions.loadSavedViewsFailure(
                    error instanceof Error ? error.message : 'Could not load saved views',
                    error
                )
            }
        },
        loadMoreSavedViews: async (_, breakpoint) => {
            if (props.teamId == null || values.savedViewsNextCursor == null) {
                actions.loadMoreSavedViewsSuccess(emptySavedViewsPage)
                return
            }
            try {
                const page = await loadDashboardSavedViews(props.teamId, values.savedViewsNextCursor)
                breakpoint()
                actions.loadMoreSavedViewsSuccess(page)
            } catch (error) {
                if (!isSavedViewsUnavailableError(error)) {
                    posthog.captureException(error)
                }
                actions.loadMoreSavedViewsFailure(
                    error instanceof Error ? error.message : 'Could not load more saved views',
                    error
                )
            }
        },
    })),
    afterMount(({ actions }) => actions.loadSavedViews()),
])
